config/routes.rb
Rails.application.routes.draw do

  root to: 'tickets#index'

  resources :tickets

  namespace :api do
    namespace :v1 do
      resources :tickets
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one :excavator

   def map_coordinates
    wellknown_text.tr('POLYGON((', '').tr('))', '').split(',').map(&:split).map do |cordinate|
      { lat: cordinate[0].to_f, lng: cordinate[1].to_f }
    end
  end

end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
  end
end

app/controllers/api/v1/tickets_controller.rb
module Api
  module V1
    class TicketsController < Api::ApiController

    def new
     @ticket = Ticket.new
     @excavator = Excavator.new
    end

    def show
      @ticket = Ticket.find(params[:id])
    end

    def create
      @ticket = Ticket.new(ticket_params)
      respond_to do |format|
        format.json do
          if @ticket.save!
            create_excavator(@ticket)
            render json: @ticket
          else
            render json: @ticket.errors, status: :unprocessable_entity
          end
        end
      end
    end

      private

      def ticket_params
        params.require(:ticket).permit(
          request_number: params[:ticket][:RequestNumber],
          sequence_number: params[:ticket][:SequenceNumber],
          request_type: params[:ticket][:RequestType],
          response_due_date_time: params[:ticket][:DateTimes][:ResponseDueDateTime],
          primary_service_area_code: params[:ticket][:ServiceArea][:PrimaryServiceAreaCode][:SACode],
          additional_service_area_codes: params[:ticket][:ServiceArea][:AdditionalServiceAreaCodes][:SACode],
          wellknown_text: params[:ticket][:ExcavationInfo][:DigsiteInfo][:WellKnownText]
        )
      end

      def create_excavator(ticket)
        ticket.create_excavator(
          company_name: params[:ticket][:Excavator][:CompanyName],address: params[:ticket][:Excavator][:Address],city: params[:ticket][:Excavator][:City],
          state: params[:ticket][:Excavator][:State],zip: params[:ticket][:Excavator][:Zip]
        )
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: :show

  def index
    @tickets = Ticket.all
  end

  def show

  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_footer.html.haml
/ footer-start
%footer.module
  .copyright
    .container
      .row
        .col-lg-12{:style => "padding-bottom: 50px;"}
          .align-center
            %p Copyright © 2018,  All Rights Reserved
/ footer-end
:javascript
  $(document).ready(function () {
      $('#horizontalTab').easyResponsiveTabs({
          type: 'default', //Types: default, vertical, accordion           
          width: 'auto', //auto or any width like 600px
          fit: true   // 100% fit in a container
      });
  });
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })

app/views/layouts/_header.html.haml
%body
  %header
    .top-head
      .container
        .row
          .col-lg-12
            %ul.notification-list
              %ul.top_nav
                %li
                  = link_to root_path do
                    = "Logo"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Coding Challege
    = csrf_meta_tags
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Titillium+Web", :rel => "stylesheet"}/
    %script{:defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyC8yq28auCimCCodKMvj3Y5RCPAenq-Rsc&libraries=places"}
    = stylesheet_link_tag 'bootstrap.min'
    = stylesheet_link_tag 'font-awesome'
    = stylesheet_link_tag 'menumaker'
    = stylesheet_link_tag 'style'
    = javascript_include_tag 'jquery.min'
    = javascript_include_tag 'bootstrap.min'
    = javascript_include_tag 'easyResponsiveTabs.js'
    = javascript_include_tag 'ie.js'
    = javascript_include_tag 'jquery.flexisel'
    = javascript_include_tag 'jquery.validate.js'
    = javascript_include_tag 'menumaker'
  :css
    .alert {
        padding: 0 !important;
      }
      .alert a {
        text-decoration: none;
      }
        .alert-notice {
          position: absolute;
          width: 100%;
          text-align: center;
          top: 0;
        }
        .alert-notice p {    
        font-size: 16px;
        width: 500px;
        margin: 0 auto;
        padding: 15px;
        margin-bottom: 20px;
        border: 1px solid transparent;
        border-radius: 4px;
        text-align: left;
    }
  %body
    = render "layouts/header"
    - flash.each do |key, value|
      %div{:class => "alert alert-#{key}"}
        %p
          %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#", :title => "close"} ×
          = value
    = yield
    = render "layouts/footer"
    = javascript_include_tag 'custom'

app/views/tickets/index.html.haml
.edit-profile
  .container
    .row
      .col-sm-12
        .profile-area
          .col-md-12
            .panel.panel-default
              .panel-heading
                %br/
                %h4 Tickets List
              .panel-body
                .box-body.table-responsive.no-padding
                  %table.table.table-hover
                    %tr
                      %th{:width => "30%"} request_number
                      %th{:width => "20%"} sequence_number
                      %th{:width => "20%"} request_type 
                      %th{:width => "50%"} response_due_date_time
                      %th{:width => "50%"} primary_service_area_code
                      %th{:width => "50%"} additional_service_area_code
                      %th{:width => "50%"}
                    - @tickets.each_with_index do |ticket,index|
                      %tr{:id => "content_#{ticket.id}"}
                        %td= ticket.request_number
                        %td= ticket.sequence_number
                        %td= ticket.request_type 
                        %td= ticket.response_due_date_time
                        %td= ticket.primary_service_area_code
                        %td= ticket.additional_service_area_code
                        %td
                          = link_to 'Show', ticket_url(ticket)
                         

app/views/tickets/show.html.haml
%meta{:content => "5", "http-equiv" => "refresh"}/

#map{:class => "#{@ticket.id}", :data => "#{@ticket.map_coordinates.to_json}"}